export type MenuItem = {
  id: string;
  kaName: string;
  enName: string;
  kaDesc: string;
  enDesc: string;
  price: number;
  img: string;
};

export type MenuCategory = {
  id: string;
  kaTitle: string;
  enTitle: string;
  items: MenuItem[];
};

export const menu: MenuCategory[] = [
  {
    id: 'pizza',
    kaTitle: 'პიცა',
    enTitle: 'Pizza',
    items: [
      {
        id: 'pepperoni-33',
        kaName: 'პიცა პეპერონი, 33 სმ',
        enName: 'Pepperoni Pizza 33 cm',
        kaDesc: 'პიცის სოუსი, სალამი, მოცარელა, პარმეზანი, რუკოლა',
        enDesc: 'Pizza sauce, salami, mozzarella, parmesan, arugula',
        price: 30,
        img: 'https://imageproxy.wolt.com/assets/67cea86c8df525635d5e0ac5?w=1600',
      },
      {
        id: 'margherita-33',
        kaName: 'პიცა მარგარიტა, 33 სმ',
        enName: 'Margherita Pizza 33 cm',
        kaDesc: 'პომიდორი, მოცარელა, პარმეზანი, რუკოლა',
        enDesc: 'Tomato, mozzarella, parmesan, arugula',
        price: 28,
        img: 'https://imageproxy.wolt.com/assets/67cf10febcb2f443170d96cb?w=1600',
      },
      {
        id: 'four-cheese-33',
        kaName: 'პიცა ოთხი ყველი, 33 სმ',
        enName: 'Four Cheese Pizza 33 cm',
        kaDesc: 'მოცარელა, პარმეზანი, ჩედარი, გორგონზოლა',
        enDesc: 'Mozzarella, parmesan, cheddar, gorgonzola',
        price: 32,
        img: 'https://imageproxy.wolt.com/assets/67cf112cbcb2f443170d96d1?w=1600',
      },
      {
        id: 'pepperoni-black-33',
        kaName: 'პიცა პეპერონი შავი ცომით, 33 სმ',
        enName: 'Pepperoni (Black Dough) 33 cm',
        kaDesc: 'პიცის სოუსი, სალამი, მოცარელა, პარმეზანი, რუკოლა',
        enDesc: 'Pizza sauce, salami, mozzarella, parmesan, arugula',
        price: 30,
        img: 'https://imageproxy.wolt.com/assets/67cea86c8df525635d5e0ac4?w=1600',
      },
       {
        id: 'margherita-black-33',
        kaName: 'პიცა მარგარიტა შავი ცომით, 33 სმ',
        enName: 'Margherita Pizza (Black Dough) 33 cm',
        kaDesc: 'პომიდორი, მოცარელა, პარმეზანი, რუკოლა',
        enDesc: 'Tomato, mozzarella, parmesan, arugula',
        price: 28,
        img: 'https://imageproxy.wolt.com/assets/67cea86c8df525635d5e0ac2?w=1600',
      },
      {
        id: 'four-cheese-black-33',
        kaName: 'პიცა ოთხი ყველი შავი ცომით, 33 სმ',
        enName: 'Four Cheese Pizza (Black Dough) 33 cm',
        kaDesc: 'მოცარელა, პარმეზანი, ჩედარი, გორგონზოლა',
        enDesc: 'Mozzarella, parmesan, cheddar, gorgonzola',
        price: 32,
        img: 'https://imageproxy.wolt.com/assets/67cea86c8df525635d5e0ac3?w=1600',
      },
    ],
  },
  {
    id: 'sandwich',
    kaTitle: 'სენდვიჩი',
    enTitle: 'Sandwich',
    items: [
      {
        id: 'brioche-club',
        kaName: 'ბრიოშის ქლაბ‑სენდვიჩი',
        enName: 'Brioche Club Sandwich',
        kaDesc: 'ბრიოში, ქათმის ფილე, მწნილი, ჩედარი და სხვა',
        enDesc: 'Brioche, chicken fillet, pickles, cheddar, etc.',
        price: 24,
        img: 'https://imageproxy.wolt.com/assets/67cf07f4cc4a3916eb963300?w=1600',
      },
      {
        id: 'panuozzo',
        kaName: 'პანუოცოს სენდვიჩი',
        enName: 'Panuozzo Sandwich',
        kaDesc: 'წითელი პესტო, რუკოლა, მოცარელა, ბეკონი, კოქტეილ სოუსი',
        enDesc: 'Red pesto, arugula, mozzarella, bacon, cocktail sauce',
        price: 26,
        img: 'https://imageproxy.wolt.com/assets/67cea99a8df525635d5e0afa?w=1600',
      },
      {
        id: 'focaccia-lori',
        kaName: 'ფოკაჩას სენდვიჩი ლორით და ჩიმჩურის სოუსით',
        enName: 'Focaccia with Lori & Chimichurri',
        kaDesc: 'პიცის ცომი, აისბერგი, ვარდისფერი პომიდორი, ჩიმიჩურის სოუსი, მწვანე ვაშლი, ბეკონი, ღორის ბარკლის შაშხი დაკეპილი, კოქტეილ სოუსი',
        enDesc: 'Pizza dough, iceberg lettuce, pink tomato, chimichurri sauce, green apple, bacon, diced pork ham, cocktail sauce',
        price: 25,
        img: 'https://imageproxy.wolt.com/assets/67ceadf98df525635d5e0bb4?w=1600',
      },
      {
        id: 'focaccia-caprese',
        kaName: 'ფოკაჩას სენდვიჩი კაპრეზე',
        enName: 'Focaccia Sandwich Caprese',
        kaDesc: 'პიცის ცომი, მწვანე პესტოს სოუსი, მოცარელა, პარმეზანი, ვარდისფერი პომიდორი, აისბერგი',
        enDesc: 'Pizza dough, green pesto sauce, mozzarella, parmesan, pink tomato, iceberg lettuce',
        price: 26,
        img: 'https://imageproxy.wolt.com/assets/67ceadf98df525635d5e0bb4?w=1600',
      },
       {
        id: 'sandwich-hunter',
        kaName: 'სენდვიჩ ჰანთერი',
        enName: 'Sandwich Hunter',
        kaDesc: 'პიცის ცომი, შერეული ხორცი(საქონელი/ღორი) 150გ, რუკოლა, პომიდორი, მოცარელა, ჩედარი, ხახვი, კოქტეილ სოუსი, ტერიაკის სოუსი',
        enDesc: 'Pizza dough, mixed meat (beef/pork) 150 g, arugula, tomato, mozzarella, cheddar, onion, cocktail sauce, teriyaki sauce',
        price: 31,
        img: 'https://imageproxy.wolt.com/assets/682476b9eae52ee4ad21677d?w=1600',
      },
    ],
  },
  {
    id: 'burger',
    kaTitle: 'ბურგერი',
    enTitle: 'Burgers',
    items: [
      {
        id: 'burger-classic',
        kaName: 'ბურგერი',
        enName: 'Classic Burger',
        kaDesc: 'ბრიოშის ცომი, შერეული ხორცი(საქონელი/ღორი) 150გ, ჩედარი, ვარდისფერი პომიდორი, კიტრის მწნილი, ბეკონი, სალათის ფოთოლი, კოქტეილ სოუსი',
        enDesc: 'Brioche dough, mixed meat (beef/pork) 150 g, cheddar, pink tomato, pickled cucumber, bacon, lettuce leaf, cocktail sauce',
        price: 30,
        img: 'https://imageproxy.wolt.com/assets/67cea86c8df525635d5e0ab8?w=1600',
      },
      {
        id: 'burger-veg',
        kaName: 'ვეგეტარიანული ბურგერი',
        enName: 'Vegetarian Burger',
        kaDesc: 'ბრიოშის ცომი, ფალაფელის ფარში, წითელი პესტოს სოუსი, ჩედარი, სალათის ფოთოლი, ვარდისფერი პომიდორი, კიტრის მწნილი, მოცარელა, კარამელიზებული ხახვი',
        enDesc: 'Brioche dough, falafel filling, red pesto sauce, cheddar, lettuce leaf, pink tomato, pickled cucumber, mozzarella, caramelized onion',
        price: 24,
        img: 'https://imageproxy.wolt.com/assets/67cea86c8df525635d5e0aba?w=1600',
      },
    ],
  },
  {
    id: 'georgian selection',
    kaTitle: 'ქართული ხაზი',
    enTitle: 'Georgian Selection',
    items: [
      {
        id: 'imeretian-khachapuri',
        kaName: 'იმერული ხაჭაპური, 24 სმ',
        enName: 'Imeretian Khachapuri 24 cm',
        kaDesc: 'იმერული, სულგუნი, მოცარელა',
        enDesc: 'Imeruli, sulguni, mozzarella',
        price: 22,
        img: 'https://imageproxy.wolt.com/assets/67cea86c8df525635d5e0abb?w=1600',
      },
      {
        id: 'lazuri-black',
        kaName: 'ლაზური ხაჭაპური შავი ცომით',
        enName: 'Lazuri (Black Dough) Khachapuri',
        kaDesc: 'შავი ცომი, ყველი, კვერცხი',
        enDesc: 'Black dough, cheese, egg',
        price: 25,
        img: 'https://imageproxy.wolt.com/assets/67cea86c8df525635d5e0abe?w=1600',
      },
      {
        id: 'lobiani-black',
        kaName: 'შავი ლობიანი, 24 სმ',
        enName: 'Lobiani Black Dough 24 cm',
        kaDesc: 'ლობიო, ჰალაპენიო',
        enDesc: 'Beans, jalapeno',
        price: 17,
        img: 'https://imageproxy.wolt.com/assets/67cea9b88df525635d5e0b01?w=1600',
      },
    ],
  },
  {
    id: 'salads',
    kaTitle: 'სალათები',
    enTitle: 'Salads',
    items: [
      {
        id: 'greek-salad',
        kaName: 'ბერძნული სალათი',
        enName: 'Greek Salad',
        kaDesc: 'ბულგარული წითელი, ბულგარული მწვანე, ფორთოხალი, ნაირფერი ჩერი პომიდორი, ფეტა, სალათის ფოთოლი, გრეიპფრუტი, მდოგვის სოუსი( მდოგვი, თაფლი, ლიმონი, ვოჩესტერი, ზეითუნის ზეთი, სოიოს სოუსი',
        enDesc: 'Red bell pepper, green bell pepper, orange, multicolored cherry tomatoes, feta, lettuce leaf, grapefruit, mustard sauce (mustard, honey, lemon, Worcestershire sauce, olive oil, soy sauce',
        price: 29,
        img: 'https://imageproxy.wolt.com/assets/67ceaa598df525635d5e0b27?w=1600',
      },
      {
        id: 'chicken-steak-salad',
        kaName: 'ქათმის სტეიკ სალათი',
        enName: 'Chicken Steak Salad',
        kaDesc: 'ქათმის ფილე, რუკოლა, აისბერგი, სალათის ფოთოლი, მზესუმზირის ზეთი, ტერიაკის სოუსი, სეზამის მარცვლები, სახამებელი, ხის სოკო',
        enDesc: 'Chicken fillet, arugula, iceberg lettuce, lettuce leaf, sunflower oil, teriyaki sauce, sesame seeds, starch, wood ear mushroom',
        price: 27,
        img: 'https://imageproxy.wolt.com/assets/67cea985cc4a3916eb961e2c?w=1600',
      },
      {
        id: 'fresh-salad-orange',
        kaName: 'ფრეშ სალათი ფორთოხლის სოუსით',
        enName: 'Fresh Salad with Orange Dressing',
        kaDesc: 'აისბერგი, რუკოლა, მწვანე ვაშლი, ავოკადო, ფორთოხლის სოუსი( ფორთოხალის წვენი, ლიმონი, კარაქი, მდოგვი, სოიოს სოუსი, ნიორი, თაფლი, სახამებელი, ) ნუშის ფანტელი, სალათის ფოთოლი, კიტრი, გრეიფრუტი',
        enDesc: 'Iceberg lettuce, arugula, green apple, avocado, orange sauce,almond flakes, lettuce leaf, cucumber, grapefruit',
        price: 16,
        img: 'https://imageproxy.wolt.com/assets/67ceaddabcb2f443170d7fd6',
      },
    ],
  },
  {
    id: 'hotdog',
    kaTitle: 'ჰოთდოგი',
    enTitle: 'Hot Dog',
    items: [
      {
        id: 'hotdog',
        kaName: 'ჰოთდოგი',
        enName: 'Hot Dog',
        kaDesc: 'ადგილზე მომზადებული ფუნთუშა; სოსისი; კოქტეილ სოუსი; ჩიმიჩურის სოუსი; ჩედარი, დამარინადებული წითელი ხახვი, კეტჩუპი',
        enDesc: 'Freshly baked bun, sausage, cocktail sauce, chimichurri sauce, cheddar, marinated red onion, ketchup',
        price: 14,
        img: 'https://imageproxy.wolt.com/assets/67e7a65b404d96b94e8a47c0?w=1600',
      },
      {
        id: 'hotdog-veg',
        kaName: 'ჰოთდოგი ვეგეტარიანული',
        enName: 'Vegetarian Hot Dog',
        kaDesc: 'ადგილზე მომზადებული ფუნთუშა; სოიოს ვეგეტარიანული სოსისი ; კოქტეილ სოუსი; ჩიმიჩურის სოუსი; ჩედარი, დამარინადებული წითელი ხახვი, კეტჩუპი',
        enDesc: 'Freshly baked bun, soy vegetarian sausage, cocktail sauce, chimichurri sauce, cheddar, marinated red onion, ketchup',
        price: 14,
        img: 'https://imageproxy.wolt.com/assets/67e7a65b404d96b94e8a47c0?w=1600',
      },
    ],
  },
  {
    id: 'breakfast',
    kaTitle: 'საუზმე',
    enTitle: 'Breakfast',
    items: [
      {
        id: 'club-sandwich-set',
        kaName: 'ქლაბ სენდვიჩის სეტი',
        enName: 'Club Sandwich Set',
        kaDesc: 'სენდვიჩი, მინი სალათი, ყავა/ჩაი',
        enDesc: 'Sandwich, mini salad, coffee/tea',
        price: 35,
        img: 'https://imageproxy.wolt.com/assets/67cf4458bcb2f443170d9a5c?w=1600',
      },
      {
        id: 'focaccia-lori-set',
        kaName: 'ფოკაჩას სენდვიჩი ლორი სეტი',
        enName: 'Focaccia Lori Set',
        kaDesc: 'სენდვიჩი, მინი სალათი, ყავა/ჩაი',
        enDesc: 'Sandwich, mini salad, coffee/tea',
        price: 35,
        img: 'https://imageproxy.wolt.com/assets/67cf41fc8df525635d5e25bf?w=960',
      },
       {
        id: 'hotdog-set-salad-coffee',
        kaName: 'ჰოთდოგი სეტი (სალათი, ყავა)',
        enName: 'Hot Dog Set (Salad & Coffee)',
        kaDesc: 'ჰოთდოგი, მინი სალათი, ყავა/ჩაი',
        enDesc: 'Hot dog, mini salad, coffee/tea',
        price: 22,
        img: 'https://imageproxy.wolt.com/assets/67cf0ecdcc4a3916eb96345c?w=960',
      },
    ],
  },
  {
    id: 'combo',
    kaTitle: 'კომბო',
    enTitle: 'Combo Meals',
    items: [
      {
        id: 'brioche-club-combo',
        kaName: 'ბრიოშის ქლაბ‑სენდვიჩის კომბო',
        enName: 'Brioche Club Sandwich Combo',
        kaDesc: 'სენდვიჩი, ფრი, გაზიანი სასმელი',
        enDesc: 'Sandwich, fries, soda',
        price: 30,
        img: 'https://imageproxy.wolt.com/assets/67cf082ccc4a3916eb96331b?w=960',
      },
      {
        id: 'focaccia-lori-combo',
        kaName: 'ფოკაჩას სენდვიჩი ლორი კომბო',
        enName: 'Focaccia Lori Sandwich Combo',
        kaDesc: 'სენდვიჩი, ფრი, გაზიანი სასმელი',
        enDesc: 'Sandwich, fries, soda',
        price: 31,
        img: 'https://imageproxy.wolt.com/assets/67cf3b02bcb2f443170d9a05?w=960',
      },
     
    ],
  },
  {
    id: 'sides-sauces',
    kaTitle: 'გარემოები & სოუსი',
    enTitle: 'Sides & Sauces',
    items: [
      {
        id: 'fries',
        kaName: 'კარტოფილი ფრი',
        enName: 'French Fries',
        kaDesc: 'კარტოფილი, კოქტეილის სოუსი',
        enDesc: 'Fries with cocktail sauce',
        price: 8,
        img: 'https://imageproxy.wolt.com/assets/67ceaa14cc4a3916eb961e67?w=960',
      },
      {
        id: 'fries-chicken-croquettes',
        kaName: 'ფრი ქათმის კროკეტებით',
        enName: 'Fries with Chicken Croquettes',
        kaDesc: 'ფრი, ქათმის კროკეტები, სოუსი',
        enDesc: 'Fries, chicken croquettes, sauce',
        price: 17,
        img: 'https://imageproxy.wolt.com/assets/67cea9d7cc4a3916eb961e43?w=960',
      },
      {
        id: 'cocktail-sauce',
        kaName: 'კოქტეილის სოუსი',
        enName: 'Cocktail Sauce',
        kaDesc: '35 გრ',
        enDesc: '35 g',
        price: 2.5,
        img: 'https://imageproxy.wolt.com/assets/680c757bf1be3b9481ced27e?w=960',
      },
      {
        id: 'teriyaki-sauce',
        kaName: 'ტერიაკის სოუსი',
        enName: 'Teriyaki Sauce',
        kaDesc: '35 გრ',
        enDesc: '35 g',
        price: 2.5,
        img: 'https://imageproxy.wolt.com/assets/680c757af1be3b9481ced27d?w=960',
      },
      {
        id: 'jalapeno-slices',
        kaName: 'ჰალაპენიო, 35 გრ',
        enName: 'Jalapeno, 35 g',
        kaDesc: 'ჰალაპენიო',
        enDesc: 'Jalapeno',
        price: 2.5,
        img: 'https://imageproxy.wolt.com/assets/680c757e11473f6ff045d4d7?w=960',
      },
      {
        id: 'pepper-jam',
        kaName: 'წიწაკის ჯემი, 35 გრ',
        enName: 'Pepper Jam, 35 g',
        kaDesc: 'მწვანე წიწაკა, ჯემი',
        enDesc: 'Pepper jam',
        price: 3,
        img: 'https://imageproxy.wolt.com/assets/680c7576f1be3b9481ced27c?w=960',
      },
    ],
  },
  {
    id: 'hot-beverages',
    kaTitle: 'ცხელი სასმელები',
    enTitle: 'Hot Beverages',
    items: [
      {
        id: 'long-black',
        kaName: 'ლონგ ბლექი',
        enName: 'Long Black Coffee',
        kaDesc: '',
        enDesc: '',
        price: 6,
        img: 'https://imageproxy.wolt.com/assets/67cf181abcb2f443170d97a4?w=960',
      },
      {
        id: 'flat-white',
        kaName: 'ფლეთ‑ვაითი',
        enName: 'Flat White',
        kaDesc: '',
        enDesc: '',
        price: 8,
        img: 'https://imageproxy.wolt.com/assets/67cf17f78df525635d5e21cb?w=960',
      },
      {
        id: 'latte',
        kaName: 'ლატე',
        enName: 'Latte',
        kaDesc: '',
        enDesc: '',
        price: 10,
        img: 'https://imageproxy.wolt.com/assets/67cead94cc4a3916eb961f85?w=960',
      },
      {
        id: 'espresso',
        kaName: 'ესპრესო',
        enName: 'Espresso',
        kaDesc: '',
        enDesc: '',
        price: 5,
        img: 'https://imageproxy.wolt.com/assets/67ceada3cc4a3916eb961f86?w=960',
      },
    ],
  },
  {
    id: 'drinks',
    kaTitle: 'სასმელი',
    enTitle: 'Drinks',
    items: [
      {
        id: 'cappy-orange',
        kaName: 'Cappy Orange 0.5 ლ',
        enName: 'Cappy Orange 0.5 L',
        kaDesc: '',
        enDesc: '',
        price: 4,
        img: 'https://imageproxy.wolt.com/assets/67ceabcbcc4a3916eb961f17?w=960',
      },
      {
        id: 'cappy-berries',
        kaName: 'Cappy Forest Berries 0.5 ლ',
        enName: 'Cappy Forest Berries 0.5 L',
        kaDesc: '',
        enDesc: '',
        price: 4,
        img: 'https://imageproxy.wolt.com/assets/67ceabd8cc4a3916eb961f1a?w=960',
      },
      {
        id: 'cappy-cherry',
        kaName: 'Cappy Cherry 0.5 ლ',
        enName: 'Cappy Cherry 0.5 L',
        kaDesc: '',
        enDesc: '',
        price: 4,
        img: 'https://imageproxy.wolt.com/assets/67ceabeccc4a3916eb961f1e?w=960',
      },
      {
        id: 'water-mtis',
        kaName: 'Water Mtis 0.5 ლ',
        enName: 'Water Mtis 0.5 L',
        kaDesc: '',
        enDesc: '',
        price: 1.5,
        img: 'https://imageproxy.wolt.com/assets/67cf1197cc4a3916eb963498?w=960',
      },
      {
        id: 'sprite',
        kaName: 'Sprite 0.33 ლ',
        enName: 'Sprite 0.33 L',
        kaDesc: '',
        enDesc: '',
        price: 3,
        img: 'https://imageproxy.wolt.com/assets/67ceac06cc4a3916eb961f22?w=960',
      },
      {
        id: 'fanta',
        kaName: 'Fanta 0.33 ლ',
        enName: 'Fanta 0.33 L',
        kaDesc: '',
        enDesc: '',
        price: 3,
        img: 'https://imageproxy.wolt.com/assets/67ceacc58df525635d5e0b8e?w=960',
      },
    ],
  },
  {
    id: 'desserts',
    kaTitle: 'დესერტი',
    enTitle: 'Dessert',
    items: [
      {
        id: 'cheesecake-san-sebastian',
        kaName: 'ჩიზქეიქი სანსებასტიანი ალუბლის სოუსით',
        enName: 'San Sebastián Cheesecake with Cherry Sauce',
        kaDesc: '',
        enDesc: '',
        price: 12,
        img: 'https://imageproxy.wolt.com/assets/67ceadc3bcb2f443170d7fce',
      },
    ],
  },
];